### ISSUE TITLE
.env example file #3

### ISSUE THREAD

**Issue by Swapnil7711** [secondbrain-fyi/secondbrain#3]
should have .env example file

**Comment by theindianappguy** [comment]
adding it now

**Comment by theindianappguy** [comment]
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
NEXT_PUBLIC_OPENAI_API_KEY=

these are the re
